version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250

  rabbitmq:
    image: rabbitmq:3.7.14-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

  #webapi:
  #  build: 
  #    context: ./
  #    dockerfile: ./WebApi/Dockerfile
  #  image: opentelemetry-example-webapi
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - RABBITMQ_HOSTNAME=rabbitmq
  #    - RABBITMQ_DEFAULT_USER=guest
  #    - RABBITMQ_DEFAULT_PASS=guest
  #    - ZIPKIN_HOSTNAME=zipkin
  #    - JAEGER_AGENT_HOST=jaeger
  #  ports:
  #    - 5000:5000
  #  depends_on:
  #    - rabbitmq
  #    - zipkin

  #workerservice:
  #  build:
  #    context: ./
  #    dockerfile: ./WorkerService/Dockerfile
  #  image: opentelemetry-example-workerservice
  #  environment:
  #    - DOTNET_ENVIRONMENT=Development
  #    - RABBITMQ_HOSTNAME=rabbitmq
  #    - RABBITMQ_DEFAULT_USER=guest
  #    - RABBITMQ_DEFAULT_PASS=guest
  #    - ZIPKIN_HOSTNAME=zipkin
  #    - JAEGER_AGENT_HOST=jaeger
  #  restart: on-failure
  #  depends_on:
  #    - rabbitmq
  #    - zipkin
